version: '3.5'

services:
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    volumes:
      - ./jenkins/data:/var/jenkins_home      
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
